services:
  yadirect-database:
    hostname: yadirect-database
    image: postgres:15.1-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - elof-yadirect-database:/var/lib/postgresql
    networks:
      nw:
        aliases:
          - yadirect-database

  yadirect-bot:
    build: ./
    command: /app/entrypoint.sh
    ports:
      - "87:8000"
    env_file:
      - .env
    volumes:
      - direct-info-static:/app/static
    depends_on:
      - yadirect-database
    networks:
      nw:
        aliases:
          - yadirect-bot

  celery:
    build: ./
    command: celery -A yandexDirectBot worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      nw:
        aliases:
          - celery

  celery-beat:
    build: ./
    command: celery -A yandexDirectBot beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - celery
    networks:
      nw:
        aliases:
          - celery-beat

  redis:
    image: redis:7.2.4-alpine
    depends_on:
      - yadirect-bot
    networks:
      nw:
        aliases:
          - redis

networks:
  nw:
  share:
    driver:
      bridge

volumes:
  elof-yadirect-database:
  direct-info-static:
