version: '3.7'
services:
  yadirect-database:
    hostname: yadirect-database
    image: postgres:15.1-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - elof-yadirect-database:/var/lib/postgresql
#    networks:
#      yadirect:
#        aliases:
#          - yadirect-database
#  strapi:
#    tty: true
#    stdin_open: true
#    ports:
#      - '9602:80'
#    networks:
#      yadirect:
#        aliases:
#          - yadirect-strapi
#    build: ./yadirect-strapi
#    env_file:
#      - .env
#    volumes:
#      - strapi_public:/app/public
#    healthcheck:
#      test:
#        [
#          'CMD-SHELL',
#          'wget -O /dev/null --no-verbose --tries=1 --spider http://localhost/_health || exit 1',
#        ]
#      interval: 3s
#      retries: 5
#      start_period: 10s
#
#  admin:
#    tty: true
#    stdin_open: true
#    ports:
#      - '9601:3000'
#    build: ./yadirect-admin
#    env_file:
#      - .env
#    networks:
#      yadirect:
#        aliases:
#          - yadirect-admin
#    command: '/bin/sh -c "yarn run build && yarn run start"'
#    healthcheck:
#      test:
#        [
#          'CMD-SHELL',
#          'wget -O /dev/null --no-verbose --tries=1 --spider http://localhost:3000 || exit 1',
#        ]
#      interval: 3s
#      retries: 5
#      start_period: 5m

networks:
  yadirect:
    external: true

volumes:
  strapi_public:
  elof-yadirect-database:
