# Generated by Django 5.0.6 on 2024-07-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandexDirectBot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yandexdirectaccount',
            name='balance',
            field=models.FloatField(blank=True, null=True, verbose_name='Баланс аккаунта'),
        ),
    ]
