# Generated by Django 5.0.6 on 2024-07-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandexDirectBot', '0003_yandexdirectaccount_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='week_budget',
        ),
        migrations.AddField(
            model_name='yandexdirectaccount',
            name='week_budget',
            field=models.IntegerField(default=0, verbose_name='Недельный бюджет'),
        ),
    ]
