# Generated by Django 5.0.7 on 2025-02-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandexDirectBot', '0006_project_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='yandexdirectaccount',
            name='monthly_budget',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Бюджет на месяц'),
        ),
    ]
