# Generated by Django 5.0.3 on 2024-06-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(verbose_name='ID чата')),
                ('name', models.CharField(max_length=100, verbose_name='Название чата')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
            },
        ),
        migrations.CreateModel(
            name='YandexDirectAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название аккаунта')),
                ('api_key', models.CharField(max_length=100, verbose_name='Ключ API')),
            ],
            options={
                'verbose_name': 'Аккаунт Яндекс.Директ',
                'verbose_name_plural': 'Аккаунты Яндекс.Директ',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_time', models.TimeField(verbose_name='Время уведомления по МСК')),
                ('chat', models.ManyToManyField(to='yandexDirectBot.chat', verbose_name='Чаты')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('week_budget', models.IntegerField(verbose_name='Недельный бюджет')),
                ('alerts', models.ManyToManyField(to='yandexDirectBot.alert', verbose_name='Уведомления')),
                ('yandex_direct_accounts', models.ManyToManyField(to='yandexDirectBot.yandexdirectaccount', verbose_name='Аккаунты Яндекс.Директ')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
